--
-- 2022/11/11
-- Billing System - Database Structure
--
--

--
-- CREATE DATABASE & ADMIN USER FOR THE APPLICATION
--

CREATE DATABASE billing;
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON billing.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;

--
-- USER MANAGEMENT
--

DROP TABLE IF EXISTS users;
CREATE TABLE users(
	name VARCHAR(140) NOT NULL PRIMARY KEY,
	username VARCHAR(140) NOT NULL UNIQUE,
	email VARCHAR(140) NOT NULL,
	password VARCHAR(140) NOT NULL,
	docstatus TINYINT(1) DEFAULT 0,
	created_by  VARCHAR(140),
	created_on  DATETIME DEFAULT CURRENT_TIMESTAMP,
	modified_by VARCHAR(140),
	modified_on DATETIME DEFAULT CURRENT_TIMESTAMP
);

